commit

diff --git a/bin/commit b/bin/commit
--- a/bin/commit
+++ b/bin/commit
@@ -5,7 +5,15 @@ if [ "`sds -rp 'konrad.bump on'`" = "commit" ]; then
 fi
 
 if [ $# -eq 0 ]; then
-    MSG="v`sds -rp version`"
+    if [ -e package.json ]; then
+        MSG="v`sds -rp version`"
+    elif [ -e ../package.json ]; then
+        MSG="v`sds -rp version`"
+    fi
+    if [ -z "$MSG" ]; then
+        echo -n '[ERROR] no commit message and no package.json!' | colorcat -p "(\[.+\])(.*)  . bgRed.bold.yellow . bold.yellow" 
+        exit 1
+    fi
 else
     MSG="$*"
 fi
